'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class Res
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CadastroDeAlunoTeste.Res", GetType(Res).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Acesso.
        '''</summary>
        Public Shared ReadOnly Property Acesso() As String
            Get
                Return ResourceManager.GetString("Acesso", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Digite o nome de um animal:.
        '''</summary>
        Public Shared ReadOnly Property Animal() As String
            Get
                Return ResourceManager.GetString("Animal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cadastrar.
        '''</summary>
        Public Shared ReadOnly Property Cadastrar() As String
            Get
                Return ResourceManager.GetString("Cadastrar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Calculadora.
        '''</summary>
        Public Shared ReadOnly Property Calculadora() As String
            Get
                Return ResourceManager.GetString("Calculadora", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Calcular.
        '''</summary>
        Public Shared ReadOnly Property Calcular() As String
            Get
                Return ResourceManager.GetString("Calcular", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Conectar.
        '''</summary>
        Public Shared ReadOnly Property Conectar() As String
            Get
                Return ResourceManager.GetString("Conectar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Deletar.
        '''</summary>
        Public Shared ReadOnly Property Deletar() As String
            Get
                Return ResourceManager.GetString("Deletar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Insira o Id que deseja apagar.
        '''</summary>
        Public Shared ReadOnly Property DeletarTexto() As String
            Get
                Return ResourceManager.GetString("DeletarTexto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Editar.
        '''</summary>
        Public Shared ReadOnly Property Editar() As String
            Get
                Return ResourceManager.GetString("Editar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Insira o Id que deseja editar.
        '''</summary>
        Public Shared ReadOnly Property EditarTexto() As String
            Get
                Return ResourceManager.GetString("EditarTexto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Escolha uma estação do ano:.
        '''</summary>
        Public Shared ReadOnly Property Estação() As String
            Get
                Return ResourceManager.GetString("Estação", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Feminino.
        '''</summary>
        Public Shared ReadOnly Property Feminino() As String
            Get
                Return ResourceManager.GetString("Feminino", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cadastro de Preferências.
        '''</summary>
        Public Shared ReadOnly Property Form() As String
            Get
                Return ResourceManager.GetString("Form", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Seu gênero:.
        '''</summary>
        Public Shared ReadOnly Property Genero() As String
            Get
                Return ResourceManager.GetString("Genero", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Id:.
        '''</summary>
        Public Shared ReadOnly Property ID() As String
            Get
                Return ResourceManager.GetString("ID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Digite sua idade:.
        '''</summary>
        Public Shared ReadOnly Property Idade() As String
            Get
                Return ResourceManager.GetString("Idade", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Limpar Campos.
        '''</summary>
        Public Shared ReadOnly Property LimparCampos() As String
            Get
                Return ResourceManager.GetString("LimparCampos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Linq.
        '''</summary>
        Public Shared ReadOnly Property Linq() As String
            Get
                Return ResourceManager.GetString("Linq", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Masculino.
        '''</summary>
        Public Shared ReadOnly Property Masculino() As String
            Get
                Return ResourceManager.GetString("Masculino", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Digite seu nome:.
        '''</summary>
        Public Shared ReadOnly Property Nome() As String
            Get
                Return ResourceManager.GetString("Nome", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Novo.
        '''</summary>
        Public Shared ReadOnly Property Novo() As String
            Get
                Return ResourceManager.GetString("Novo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Preencha os campos antes de cadastrar.
        '''</summary>
        Public Shared ReadOnly Property NovoTexto() As String
            Get
                Return ResourceManager.GetString("NovoTexto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Outro.
        '''</summary>
        Public Shared ReadOnly Property Outro() As String
            Get
                Return ResourceManager.GetString("Outro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Primavera.
        '''</summary>
        Public Shared ReadOnly Property Primavera() As String
            Get
                Return ResourceManager.GetString("Primavera", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Insira dois valores:.
        '''</summary>
        Public Shared ReadOnly Property TextoCalculadora() As String
            Get
                Return ResourceManager.GetString("TextoCalculadora", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
